#!/usr/bin/env python3

"""
Run the project tests.

This is a simple wrapper around pytest, equivalent to running
'python -m pytest tests/'.
"""

import sys

import pytest


rc = pytest.main(sys.argv[1:])
sys.exit(rc)
