####################
## DO NOT EDIT THIS FILE (NOT EVEN THE FILENAME) OR IT WILL STOP WORKING
####################
"""Resources to run encrypted python files."""

from types import ModuleType
import logging

from decryptor import get_key

from cryptography.fernet import Fernet


key = get_key()
del get_key

def decrypt_file(fstring):
    cipher = Fernet(key)
    byte_string = cipher.decrypt(bytes(fstring, 'utf8'))
    return byte_string.decode() #return string (not bytes)

def make_module(fstring, preexisting_globals={}):
    module = ModuleType('module') #instantiate
    # Decrypt the file to obtain a python module in string form
    decrypted_file = decrypt_file(fstring)
    exec_str = ''
    for var in ['__file__', '__name__', '__package__']:
        value = preexisting_globals[var]
        exec_str += '{} = r\'{}\'\n'.format(var, value)
    exec_str += decrypted_file
    exec(exec_str, module.__dict__) #execute the code in created module
    del decrypted_file, exec_str #to be sure it can't be accessed
    # sys.modules[module_name] = module #make it importable
    return module
